task_manager/labels/urls.py
from django.urls import path

from .views import (
    LabelCreateView,
    LabelDeleteView,
    LabelsIndexView,
    LabelUpdateView,
)

app_name = 'labels'

urlpatterns = [
    path('', LabelsIndexView.as_view(), name='index'),
    path('create/', LabelCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', LabelDeleteView.as_view(), name='delete'), 
    path('<int:pk>/update/', LabelUpdateView.as_view(), name='update'),
]

task_manager/tasks/urls.py
from django.urls import path

from .views import (
    TaskCreateView,
    TaskDeleteView,
    TasksIndexView,
    TaskUpdateView,
    TaskView,
)

app_name = 'tasks'

urlpatterns = [
    path('', TasksIndexView.as_view(), name='index'),
    path('create/', TaskCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', TaskView.as_view(), name='task'), 
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='update'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.users.forms import UserFormLogin

# my views
from task_manager.views import HomePageView, MyLoginView, MyLogoutView

urlpatterns = [
    path('', HomePageView.as_view(), name='root'),
    path('admin/', admin.site.urls),
    path('login/', MyLoginView.as_view(
        template_name="registration/login.html",
        authentication_form=UserFormLogin,
    ), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('users/', include('task_manager.users.urls')),
]

task_manager/users/urls.py
from django.urls import path


from task_manager.users.views import (
    UserCreateView,
    UserDeleteView,
    UsersIndexView,
    UserUpdateView,
)

app_name = 'users'

urlpatterns = [
    path('', UsersIndexView.as_view(), name='users'),
    path('create/', UserCreateView.as_view(), name='create'),  
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),  
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
]

task_manager/labels/models.py
from django.db import models

# Create your models here.
class Label(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'labels'
    
    def __str__(self):
        return self.name

task_manager/users/models.py
# task_manager/users/models.py
# from django.db import models

# Create your models here.

task_manager/labels/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.functions import attrs_add

from .models import Label


class LabelForm(ModelForm):
    class Meta:
        model = Label
        fields = ["name"]
        labels = {
            'name': _("Name"),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        placeholders = {
            'name': _("Name")
        }
        
        attrs_add(self.fields, placeholders)

task_manager/labels/views.py
from django.contrib import messages
from django.db.models import ProtectedError
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import ListView

from task_manager.mixins import RequireMessageMixin

from .forms import LabelForm
from .models import Label


# Create your views here.
# path ''
class LabelsIndexView(RequireMessageMixin, ListView):
    model = Label
    template_name = "labels/index.html"
    context_object_name = "labels"


# path 'create/'
class LabelCreateView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        form = LabelForm()
        context = {
            "form": form,
            "button": _("Create"),
        }
        return render(request, "labels/create.html", context)
        
    def post(self, request, *args, **kwargs):
        form = LabelForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("The label was created successfully"))
            return redirect('labels:index') 
        context = {
            'form': form,
            'button': _("Create"),
        }
        return render(request, 'labels/create.html', context)


# path 'delete'
class LabelDeleteView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        label_pk = kwargs.get('pk')
        name = Label.objects.get(pk=label_pk).name
        context = {
            "label_pk": label_pk,
            "name": name,
        }
        return render(
            request,
            "labels/delete.html",
            context
        )
    
    def post(self, request, *args, **kwargs):
        label_pk = kwargs.get('pk')
        label = Label.objects.get(pk=label_pk)
        if label.tasks.exists():
            messages.error(
                request,
                _("It is not possible to delete a label "
                    "because it is being used"))
            return redirect('labels:index')
        else:
            label.delete()
            messages.success(request, _("Label successfully deleted"))
            return redirect('labels:index')



# path 'update/'
class LabelUpdateView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        label_pk = kwargs.get('pk')
        label = Label.objects.get(pk=label_pk)
        form = LabelForm(instance=label)
        context = {
            "form": form,
            "label_pk": label_pk,
            "button": _("Edit"),
        }
        return render(
            request,
            "labels/update.html",
            context,
        )

    def post(self, request, *args, **kwargs):
        label_pk = kwargs.get('pk')
        
        label = Label.objects.get(pk=label_pk)
        form = LabelForm(request.POST, instance=label)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("Label successfully edited"))
            return redirect('labels:index')
        context = {
            'form': form,
            "button": _("Edit"),
            }

        return render(request, 'labels/update.html', context)
    

task_manager/statuses/views.py
from django.contrib import messages
from django.db.models import ProtectedError
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import ListView

from task_manager.mixins import RequireMessageMixin

from .forms import StatusForm
from .models import Status


# Create your views here.
# path ''
class StatusIndexView(RequireMessageMixin, ListView):
    model = Status
    template_name = "statuses/index.html"
    context_object_name = "statuses"


# path 'create/'
class StatusCreateView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        form = StatusForm()
        context = {
            "form": form,
            "button": _("Create"),
        }
        return render(request, "statuses/create.html", context)
        
    def post(self, request, *args, **kwargs):
        form = StatusForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("The status was created successfully"))
            return redirect('statuses:statuses') 
        context = {
            'form': form,
            'button': _("Create"),
        }
        return render(request, 'statuses/create.html', context)


# path 'delete'
class StatusDeleteView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        status_pk = kwargs.get('pk')
        name = Status.objects.get(pk=status_pk).name
        context = {
            "status_pk": status_pk,
            "name": name,
        }
        return render(
            request,
            "statuses/delete.html",
            context
        )
    
    def post(self, request, *args, **kwargs):
        status_pk = kwargs.get('pk')
        status = Status.objects.get(pk=status_pk)
        if status:
            try:
                status.delete()
            except ProtectedError:
                messages.error(
                    request,
                    _("It is not possible to delete a status "
                        "because it is being used"))
                return redirect('statuses:statuses')
            messages.success(request, _("Status successfully deleted"))
            return redirect('statuses:statuses')
        messages.error(request, _('Oops'))
        return redirect('statuses:statuses')


# path 'update/'
class StatusUpdateView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        status_pk = kwargs.get('pk')
        status = Status.objects.get(pk=status_pk)
        form = StatusForm(instance=status)
        context = {
            "form": form,
            "status_pk": status_pk,
            "button": _("Edit"),
        }
        return render(
            request,
            "statuses/update.html",
            context,
        )

    def post(self, request, *args, **kwargs):
        status_pk = kwargs.get('pk')
        
        status = Status.objects.get(pk=status_pk)
        form = StatusForm(request.POST, instance=status)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("Status successfully edited"))
            return redirect('statuses:statuses')
        context = {
            'form': form,
            "button": _("Edit"),
            }

        return render(request, 'statuses/update.html', context)
    

task_manager/tasks/views.py
# task_manager/tasks/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views import View
from django_filters.views import FilterView

from task_manager.mixins import (
    LoginRequiredMixin,
    RequireMessageMixin,
    TaskPermissionMixin,
)

from .filter import TaskFilter
from .forms import TaskForm
from .models import Task


# Create your views here.
# path ''
class TasksIndexView(RequireMessageMixin, FilterView):
    model = Task
    template_name = "tasks/index.html"
    filterset_class = TaskFilter


# path '<int:pk>/create/'
class TaskCreateView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        form = TaskForm()
        context = {
            "form": form,
            "button": _("Create"),
        }
        return render(request, "tasks/create.html", context)
        
    def post(self, request, *args, **kwargs):
        form = TaskForm(request.POST or None, user=request.user)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("The task was created successfully"))
            return redirect('tasks:index') 
        context = {
            'form': form,
            'button': _("Create"),
        }
        return render(request, 'tasks/create.html', context)


# path '<int:pk>/delete'
class TaskDeleteView(TaskPermissionMixin, View):
    def get(self, request, *args, **kwargs):
        task_pk = kwargs.get('pk')
        task = Task.objects.get(pk=task_pk)
        context = {
            "task_pk": task_pk,
            "name": task.name,
        }
        return render(
            request,
            "tasks/delete.html",
            context
        )
    
    def post(self, request, *args, **kwargs):
        status_pk = kwargs.get('pk')
        status = Task.objects.get(pk=status_pk)
        if status:
            status.delete()
            messages.success(request, _("Task successfully deleted"))
            return redirect('tasks:index')
        messages.error(request, _('Oops'))
        return redirect('tasks:index')


# path '<int:pk>/update/'
class TaskUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        task_pk = kwargs.get('pk')
        status = Task.objects.get(pk=task_pk)
        form = TaskForm(instance=status)
        context = {
            "form": form,
            "task_pk": task_pk,
            "button": _("Edit"),
        }
        return render(
            request,
            "tasks/update.html",
            context,
        )

    def post(self, request, *args, **kwargs):
        task_pk = kwargs.get('pk')
        
        task = Task.objects.get(pk=task_pk)
        form = TaskForm(request.POST, instance=task)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("Task successfully edited"))
            return redirect('tasks:index')
        context = {
            'form': form,
            "button": _("Edit"),
            }

        return render(request, 'tasks/update.html', context)
    

# path '<int:pk>/'
class TaskView(RequireMessageMixin, View):
    def get(self, request, *args, **kwargs):
        task_pk = kwargs.get('pk')
        task = Task.objects.get(pk=task_pk)
        context = {
            "task": task,
        }
        return render(request, "tasks/show_task.html", context)

task_manager/users/views.py
# task_manager/users/views.py
# Create your views here.
# from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db.models import ProtectedError
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import ListView

from task_manager.mixins import UserPermissionMixin

from .forms import UserFormCreate


# path ''
class UsersIndexView(ListView):
    model = User
    template_name = "users/index.html"
    context_object_name = "users"


# path 'create/'
class UserCreateView(View):
    def get(self, request, *args, **kwargs):
        form = UserFormCreate()
        context = {
            'form': form,
            'button': _("Register"),
        }
        return render(request, "users/create.html", context)
        
    def post(self, request, *args, **kwargs):
        form = UserFormCreate(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _("User successfully registered"))
            return redirect('login')
        context = {
            'form': form,
            'button': _("Register"),
        }

        return render(request, 'users/create.html', context)


# path 'delete'
class UserDeleteView(UserPermissionMixin, View):
    def get(self, request, *args, **kwargs):
        user_pk = kwargs.get('pk')
        username = User.objects.get(pk=user_pk).username
        context = {
            "user_pk": user_pk,
            "username": username,
        }
        return render(
            request,
            "users/delete.html",
            context
        )
    
    def post(self, request, *args, **kwargs):
        user_pk = kwargs.get('pk')
        user = User.objects.get(pk=user_pk)
        if user:
            try:
                user.delete()
            except ProtectedError:
                messages.error(
                    request,
                    _("It is not possible to delete a user "
                        "because it is being used"))
                return redirect('users:index')
            messages.success(request, _("User successfully deleted"))
            return redirect('users:index')  # Редирект на указанный маршрут
        messages.error(request, _('Oops'))
        return redirect('users:index')


# path 'update/'
class UserUpdateView(UserPermissionMixin, View):
    def get(self, request, *args, **kwargs):
        user_pk = kwargs.get('pk')
        user = User.objects.get(pk=user_pk)
        form = UserFormCreate(instance=user)
        context = {
            "form": form,
            "user_pk": user_pk,
            "button": _("Edit"),
        }
        return render(
            request,
            "users/update.html",
            context,
        )

    def post(self, request, *args, **kwargs):
        user_pk = kwargs.get('pk')
        
        if request.user.pk != user_pk:
            raise PermissionDenied()
        user = User.objects.get(pk=user_pk)
        form = UserFormCreate(request.POST, instance=user)
        
        if form.is_valid():
            form.save()
            messages.success(request, _("User successfully edited"))
            return redirect('users:index')
        
        context = {
            'form': form,
            "button": _("Edit"),
        }
        return render(request, 'users/update.html', context)

task_manager/views.py
# task_manager/views.py

from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.utils.translation import gettext as _
from django.views.generic import TemplateView

from .users.forms import UserFormLogin


class HomePageView(TemplateView):
    template_name = 'root.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class MyLoginView(LoginView):
    form_class = UserFormLogin
    template_name = "registration/login.html"

    def form_valid(self, form):
        messages.success(self.request, _("Logged in successfully"))
        return super().form_valid(form)
    

class MyLogoutView(LogoutView):
    next_page = '/'

    def dispatch(self, request, *args, **kwargs):
        messages.success(request, _("You have logged out"))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/tasks/create.html
<!--tasks/create.html-->
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">{% trans "Create task" %}</h1>

  {% include "form.html" %}

</div>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">{% trans "Delete a task" %}</h1>
  <p>
    Are you sure you want to delete {{ name }}
  </p>
  <form action="{% url 'tasks:delete' task_pk %}" method="post" class="mb-3">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">
      {% trans "Yes, delete" %}
    </button>

  </form>
</div>
{% endblock %}

task_manager/templates/tasks/filter.html
<!--filter/update.html-->
{% extends "base.html" %}
{% load i18n %}

{% block content %}



<div class="container wrapper flex-grow-1">
  <h1>{% trans "Tasks" %}</h1>
  <a class="btn btn-primary  mb-3" href="{% url 'tasks:create' %}">{% trans "Create task" %}</a>
  <div class="card  mb-3">
    <div class="card-body bg-light">
        <form method="get" class="mb-3">

        {% for field in filter.form %}
            <div class="mb-3">
                           
                {{ field }} 
                {{ field.label_tag }}                      
                {% if field.help_text %}
                <div class="form-text">
                    {{ field.help_text }}
                </div>
                {% endif %}
                {% for error in field.errors %}
                <div class="text-danger">
                    {{ error }}
                </div>
                {% endfor %}
            </div>
            {% endfor %}

  <button type="submit" class="btn btn-primary">Показать</button>
</form>
</div> 
</div>

    <table class="table table-striped mt-2">
      <thead>
        <tr>
          <th>ID</th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Status" %}</th>
          <th>{% trans "Author" %}</th>
          <th>{% trans "Executor" %}</th>
          <th>{% trans "Creation date" %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for task in filter.qs %}
        <tr>
          <td>{{ task.id }}</td>
          <td>{{ task.name }}</td>
          <td>{{ task.status }}</td>
          <td>{{ task.author }}</td>
          <td>{{ task.executor }}</td>
          <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
          <td>
            <a href="{% url 'tasks:update' task.pk %}">{% trans "Edit" %}</a>
            <br><a href="{% url 'tasks:delete' task.pk %}">{% trans "Delete" %}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>



</div>
{% endblock %}

task_manager/templates/tasks/index.html
<!-- task_manager/templates/tasks/index.html -->
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <div class="container wrapper flex-grow-1">
    <h1>{% trans "Tasks" %}</h1>
    <a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}">{% trans "Create task" %}</a>
    <!-- filter -->
    <div class="card  mb-3">
      <div class="card-body bg-light">
          <form method="get" class="mb-3">
          {% for field in filter.form %}
              <div class="mb-3">
                {% if field.name == "self_tasks" %} 
                  {{ field }}
                  {{ field.label_tag }} 
                {% else %}
                  {{ field.label_tag }}
                  {{ field }}
                {% endif %}                                     
                
                {% for error in field.errors %}
                  <div class="text-danger">
                      {{ error }}
                  </div>
                  {% endfor %}
              </div>
              {% endfor %}
              <button type="submit" class="btn btn-primary">{% trans "Show" %}</button>
          </form>
      </div> 
    </div>

    <!-- filner end -->
    
    <table class="table table-striped mt-2">
      <thead>
        <tr>
          <th>ID</th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Status" %}</th>
          <th>{% trans "Author" %}</th>
          <th>{% trans "Executor" %}</th>
          <th>{% trans "Creation date" %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for task in filter.qs %}
        <tr>
          <td>{{ task.id }}</td>
          <td>
            <a href="{% url 'tasks:task' task.pk %}">{{ task.name }}</a>
          </td>
          <td>{{ task.status }}</td>
          <td>{{ task.author }}</td>
          <td>{{ task.executor }}</td>
          <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
          <td>
            <a href="{% url 'tasks:update' task.pk %}">{% trans "Edit" %}</a>
            <br><a href="{% url 'tasks:delete' task.pk %}">{% trans "Delete" %}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


{% endblock %}

task_manager/templates/tasks/show_task.html
<!-- task_manager/templates/tasks/show_task.html -->
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">
  {% trans "Task view" %}
  </h1>
  <div class="card">
    <div class="card-header bg-secondary text-white">
      <h2>{{ task.name }}</h2>
    </div>
    <div class="card-body bg-light">
      <p>{{ task.description }}</p>
      <hr>
      
      <div class="container">
        <div class="row p-1">
          <div class="col">{% trans "Author" %}</div>
          <div class="col">{{ task.author.get_full_name|default:task.author.username }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% trans "Executor" %}</div>
          <div class="col">{{ task.executor }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% trans "Status" %}</div>
          <div class="col">{{ task.status }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% trans "Creation date" %}</div>
          <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
        </div>
        <div class="row p-1">
          <div class="col">
            <h6>{% trans "Labels" %}</h6>
            <ul>
              {% for label in task.labels.all %}
                <li>{{ label.name }}</li> 
              {% endfor %}          
            </ul>
          </div>
        </div>
        <div class="row p-1">
          <div class="col">
            <a href="{% url 'tasks:update' task.pk %}">{% trans "Edit" %}</a>
            <br>
            <a href="{% url 'tasks:delete' task.pk %}">{% trans "Delete" %}</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/tasks/update.html
<!--tasks/create.html-->
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">{% trans "Changing the status" %}</h1>

  {% include "form.html" %}

</div>
{% endblock %}